# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON', '~> 5.0.0'
  # Pods for VKClient
  pod 'RealmSwift'
  pod 'Kingfisher', '~> 5.0'
  # add the Firebase pod for Google Analytics
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Auth'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods


end
